마켓 상세페이지 API 연결
hyunyeee/mju-market pull request #10
Opened 2024-03-13 21:23 UTC by hyunyeee

## 📄 Summary
메인페이지에서 클릭한 상품에 해당하는 상세페이지로 이동하고 해당 데이터를 불러온다.

## 🙋🏻 More
useContext 사용해서 구현했는데 추후에 Zustand 사용해서 리팩토링할 계획 있습니다.

close #8

2024-03-14 07:35 UTC, ndaemy commented on src/pages/Market.tsx
> +export interface Iproduct {
1. interface 나 type 에서는 PascalCase 를 쓰는 것이 convention인데, PascalCase 대로라면 IProduct 가 맞습니다.
2. Hungarian notation (헝가리안 표기법) 은 요즘 잘 안쓰이는 방법입니다. [참고](https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript/41967120#41967120)

2024-03-14 07:35 UTC, ndaemy commented on src/pages/Detail.tsx
> +}
일반적인 경우 file 의 top-level 에 존재하는 interface 나 const 등은 사이에 blank line 하나를 넣습니다. 반드시 지켜야 할 필요는 없지만, 프로젝트 내에서는 통일성을 가지는게 좋아요.

2024-03-14 07:35 UTC, ndaemy commented on src/pages/Detail.tsx
> +  margin: 0 -20px;
x-axis 가 음수의 margin을 가지는거 의도인거죠..?

2024-03-14 07:35 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
>  interface clickedStyle {
아래에서도 이미 작성한 피드백인데, interface 나 type 은 PascalCase 를 쓰는 것이 convention 입니다

2024-03-14 07:35 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +  const productContext = useContext(ProductContext);
사용처가 하나뿐인 것 같은데, 그렇다면 destructuring 을 하면 코드가 더 깔끔해질 수 있을 것 같아요.

2024-03-14 07:35 UTC, ndaemy commented on src/components/UI/market/ProductListItem.tsx
> +    <ItemBox onClick={() => clickItem()}>
1. 아래 정도로 줄여서 쓸 수도 있습니다
```suggestion
    <ItemBox onClick={clickItem}>
```

2. onClick handler 함수의 네이밍은 on\*Click 혹은 handle\*Click 의 형태를 많이 사용해요. (ex. onItemClick) 조금 오래된 글이지만 참고해보시면 좋을듯합니다. [참고](https://jaketrent.com/post/naming-event-handlers-react/)

2024-03-14 07:35 UTC, ndaemy commented on src/components/UI/market/ProductListItem.tsx
> +  const productContext = useContext(ProductContext);
여기도 사용처가 한 곳 뿐이라면, destructuring 을 통해 간결히 쓸 수 있습니다.

2024-03-14 07:35 UTC, ndaemy commented on src/components/UI/market/ProductActionBar.tsx
> +    <Container {...atterProps}>
👍

2024-03-14 07:35 UTC, ndaemy commented on src/api/market.ts
> +    }
함수 이름이 getProduct 인데, 여기서 navigate 까지 하는건 역할 분리가 잘 되지 않는 것 같아요. catch 를 조금 더 상위로 이동시킬 필요가 있습니다.

2024-03-14 07:35 UTC, ndaemy commented on src/api/market.ts
> +const token = localStorage.getItem('token');
localStorage.getItem 은 null 을 반환할 수도 있습니다. 이에 따른 handling 이 필요해보여요.

2024-03-14 07:35 UTC, ndaemy commented on src/ProductContext.ts
> +interface IProductContext {
hungarian notation 은 요즘은 잘 쓰이지 않습니다. 아래 리뷰를 확인해보시면 좋을듯해요.

2024-03-17 19:07 UTC, hyunyeee commented on src/pages/Market.tsx
> +export interface Iproduct {
수정했습니다 !!

2024-03-17 19:11 UTC, hyunyeee commented on src/pages/Detail.tsx
> +}
수정했습니다!!

2024-03-17 19:14 UTC, hyunyeee commented on src/pages/Detail.tsx
> +  margin: 0 -20px;
넵 상위 컴포넌트에서 전체적으로 padding 20px 주고있어서 상쇄 시키려고 가로 margin 20px 주었습니다!

2024-03-17 19:14 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
>  interface clickedStyle {
넵 수정했습니다!!

2024-03-17 19:27 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
> +  const productContext = useContext(ProductContext);
수정했습니다 !!! (｡･ρ･)

2024-03-17 19:32 UTC, hyunyeee commented on src/components/UI/market/ProductListItem.tsx
> +    <ItemBox onClick={() => clickItem()}>
수정했습니다!!!

2024-03-17 19:38 UTC, hyunyeee commented on src/components/UI/market/ProductListItem.tsx
> +  const productContext = useContext(ProductContext);
수정했습니다!!

2024-03-17 20:16 UTC, hyunyeee commented on src/api/market.ts
> +    }
수정했습니다 !!! ✧و(•’v‘•)

2024-03-18 08:48 UTC, hyunyeee commented on src/api/market.ts
> +const token = localStorage.getItem('token');
수정 했습니다! ✧و(•’v‘•)

2024-03-18 08:50 UTC, hyunyeee commented on src/ProductContext.ts
> +interface IProductContext {
수정 했습니다 !!

2024-03-18 09:52 UTC, ndaemy requested changes
대부분은 나중에 공부하거나 수정해도 되는건데, 몇몇 부분이 (예를 들면 PascalCase, camelCase 라던가) 지금 수정을 요하는것들이라 Request changes 남겨여
적당히 수정하고 커밋하면 approve 해둘게여

2024-03-18 09:52 UTC, ndaemy commented on src/components/AppRoutes.tsx
이렇게 별도의 RoutesContainer 라는 파일을 만들거라면, 아래처럼 하는 것도 방법입니다

- 현재 App.js 에서 BrowserRouter로 감싸는 부분을 index.js 로 보내고
- 현재 AppRoutes.js 에 있는 내용들을 App.js 로 보내고

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Market.tsx
이번에 수정한 부분이 아니라서 리뷰를 못달아서 여기다가 달아요
L21 의 length !== 0 이라는 코드가 불필요해요
어차피 map 할 때 length 가 0이면 return 을 아무것도 안하니까여

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +  const { content, ownerId, price, productId, title } = productObj || {};
쓰이지 않는 객체는 굳이 destructuring 할 필요가 없어여
productId 가 쓰이지 않고 있길래!

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +  const { content, ownerId, price, productId, title } = productObj || {};
\+ 이럴거라면 아예 productObj 의 initialValue 를 빈 객체({}) 로 주면 편하지 않을까?

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +    }
지금 당장 급한건 아니지만, catch 에서 모든 에러를 handling 하지 않으면 사용자 입장에서 뭔가 에러가 터졌는데 무반응인 상황이 발생할 수도 있어
처리하지 않을거라면 다시 throw 해주는게 나아 상위 Error Boundary 에서 처리될 수 있도록!

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +          navigate('/login');
나중에 UX 를 고려하자면 "로그인 세션이 만료되었습니다" 같은 토스트를 띄워주는것도 좋을듯

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +        navigate('/login');
나중에 UX 를 고려하자면 "로그인 먼저 해주세요" 같은 토스트를 띄워주는것도 좋을듯

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +  const productContext = useContext(ProductContext);
구두로 설명 완완
이왕이면 서버 API 주소가 바뀌었으면 하는 방향으로

2024-03-18 09:52 UTC, ndaemy commented on src/pages/Detail.tsx
> +  const productContext = useContext(ProductContext);
\+ destructuring 생활화!

2024-03-18 09:52 UTC, ndaemy commented on src/ProductContext.ts
구두로 설명 완완
Context 는 진짜 필요한거 아니면 안쓰는게 좋다 메모 📝

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
selectCategoryProps 가 PascalCase 가 아니에요!

2024-03-18 09:52 UTC, ndaemy commented on src/api/market.ts
> +export const getProducts = async (token: string | null, categoryId: number) => {
token이 string | null 이라면 null 일 때의 처리를 좀 해줘야 할듯해요
지금 코드대로라면 null 일 때 서버로 빈 토큰이 날아가버리는 이슈가 있어서, null 이면 에러를 throw 하거나 하는 방향으로 코드 짜보는 것도 좋을듯!

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/ProductActionBar.tsx
> +  price: number | undefined;
얘는 undefined 인 경우가 있으면 안될거같아요
undefined 인채로 props 가 넘어온다면 불필요하게 컴퍼넌트 렌더링은 되는데 이상한 값이 보일거니까!
차라리 undefined 경우를 받지 말고, 이 컴퍼넌트를 호출하는 곳에서 undefined 면 호출하지 않도록 하는 코드가 나아보여요

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/ProductListItem.tsx
> +    setProductId(productId);
요거 구두로 얘기한 부분과 겹치는데, productId 를 명시적으로 set 하는건 좋지 않아요. 주소창의 productId 랑 다를 수 있다는 여지가 생겨버리니까요.
주소창에서 useParams 를 통해 읽어오는것이 바람직할듯!

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
dummy_category 는 camelCase 가 아니에요!

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +        navigate('/login');
경우에 따라서는 navigate 함수의 두 번째 인자로 { replace: true } 옵션을 줘야 할 때도 있어요. 나중에 시간 될 때 왜 / 언제 쓰는건지 알아보면 좋을듯!

2024-03-18 09:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
clickedStyle 이 PascalCase 가 아니에요!

2024-03-19 06:03 UTC, hyunyeee commented on src/pages/Detail.tsx
> +  const { content, ownerId, price, productId, title } = productObj || {};
initiaState undefinded로 안두고 빈 객체로 주면 타입 에러 나는데 지금 해둔 거 말고 어떻게 해야 될 지 잘 모르겠습니다..!!

타입 에러 나는 이유가 ProductDetail interface에서 전부 필수 필드로 지정해서 그런 거 같은데 맞을까요?

2024-03-19 08:46 UTC, hyunyeee commented on src/pages/Detail.tsx
> +  const productContext = useContext(ProductContext);
넵 이거 바꿔준다고 하셔서 바뀌고 나면 수정하겠습니다  (•͈ᴗ•͈) ✧و(•’v‘•)

2024-03-19 08:46 UTC, hyunyeee commented on src/ProductContext.ts
넵넵 (๑❛v❛๑)☆

2024-03-19 08:54 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
매의 눈 감사함니다 ......ㅎ

2024-03-19 16:54 UTC, ndaemy commented on src/pages/Detail.tsx
> +  const { content, ownerId, price, productId, title } = productObj || {};
아 그러네 {} 가 ProductDetail 타입에 호환이 안되는구나.. 나도 잠깐 헷갈렸다
그러면 위에는 지금 상태가 맞을듯! 근데 대신에 state 선언부를 아래 정도로 간소화할 수는 있어

```typescript
const [productObj, setProductObj] = useState<ProductDetail>();  // 이러면 productObj 의 타입은 ProductDetail | undefined
```

2024-03-19 19:08 UTC, hyunyeee commented on src/api/market.ts
> +export const getProducts = async (token: string | null, categoryId: number) => {
에러 throw하게 고쳐봤는데 봐주시면 감사하겠습니다 ,, (•͈ᴗ•͈)

2024-03-19 19:22 UTC, hyunyeee commented on src/components/UI/market/ProductListItem.tsx
> +    setProductId(productId);
수정 완완 했습니다 ✧و(•’v‘•)

2024-03-19 19:40 UTC, hyunyeee commented on src/components/UI/market/ProductActionBar.tsx
> +  price: number | undefined;
undefined 지우고 price = 0를 주어서 고쳐봤습니다!

2024-03-19 19:46 UTC, hyunyeee commented on src/pages/Detail.tsx
> +  const { content, ownerId, price, productId, title } = productObj || {};
우악 감사합니다 !! ヽ(´∀｀)八(´∀｀)ノ

2024-03-20 17:51 UTC, ndaemy approved these changes
몇몇 리뷰를 남기긴 했는데 크리티컬한건 안보여서 approve 합니다~

2024-03-20 17:51 UTC, ndaemy commented on src/api/market.ts
> +export const getProducts = async (token: string | null, categoryId: number) => {
흠.. 근데 함수의 선언부를 아래처럼 하고 token 이 없을 땐 아예 이 함수를 호출하지 않도록 만드는게 낫지 않을까 싶어요!
```suggestion
export const getProducts = async (token: string, categoryId: number) => {
```

2024-03-20 17:51 UTC, ndaemy commented on src/api/market.ts
> +  token: string | null,
위 리뷰와 마찬가지!

2024-03-20 17:51 UTC, ndaemy commented on src/components/UI/market/ProductActionBar.tsx
> +const ProductActionBar: React.FC<Price> = ({ price, ...attrProps }) => {
이거 이러면 attrProps 를 못받을텐데.. 타입스크립트 타입상 그냥 빈 객체만 가능할테니까!
진짜 attrProps 를 받을거라면 추가 작업이 필요해

2024-03-20 17:51 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +    }
1. else if 가 이럴거면 two depth 로 가지 말고 합쳐도 될듯!
2. catch 에서 아무 처리를 하지 않은 경우는 다시 throw 해주거나 하는 식으로 처리해야 할듯!

2024-03-20 17:51 UTC, ndaemy commented on src/index.tsx
> +  </ThemeProvider>,
React.StrictMode 를 없앤건 의도된건가..?

2024-03-20 17:51 UTC, ndaemy commented on src/pages/Detail.tsx
> +        Number(productId),
Number() 함수는 숫자가 아닌 경우 NaN 을 return 하는데, 이거에 대한 처리가 되어있어야 할듯!

2024-03-20 18:18 UTC, hyunyeee commented on src/api/market.ts
> +  token: string | null,
어???????.....!!!!!!!!! 감사합니다!!!

2024-03-20 18:28 UTC, hyunyeee commented on src/components/UI/market/ProductActionBar.tsx
> +const ProductActionBar: React.FC<Price> = ({ price, ...attrProps }) => {
이거 ..... styled-components 확장 때문에 attrProps 사용한건데 지우면 스타일 확장 적용이 안돼서요 ,,, 어떻게 바꿔야 될까요?!

2024-03-20 18:30 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
> +    }
수정 완완 했습니다!! (๑❛v❛๑)☆

2024-03-20 18:33 UTC, hyunyeee commented on src/index.tsx
> +  </ThemeProvider>,
엇 ,,ㅎ console 두 번 찍히는 거 싫어서 지웠는데 살리겠습니다...! (›´-‹ )

2024-03-21 07:48 UTC, hyunyeee commented on src/pages/Detail.tsx
> +        Number(productId),
수정했습니다 !!

2024-03-21 07:59 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
> +        navigate('/login');
우악 . 감사합니다 !!!!! 적용 했습니다 (･ω･)

2024-03-22 12:06 UTC, ndaemy commented on src/api/auth.ts
> +  const response = await Axios.post(`/api/${path}`, {
TypeScript 와 axios 를 같이 쓸 땐 generic 으로 response type 을 선언해두는걸 추천합니다
작년 2학기 세션을 확인해보도록

2024-03-22 12:06 UTC, ndaemy commented on src/api/auth.ts
> +    return response.data.token;
이러면 eslint 의 [consistent-return](https://eslint.org/docs/latest/rules/consistent-return) 규칙에 위배됩니다. 한 번 찾아보시길

2024-03-24 12:50 UTC, hyunyeee commented on src/api/auth.ts
> +  const response = await Axios.post(`/api/${path}`, {
넵 감사합니다 !!!~~~~~

2024-03-24 13:42 UTC, hyunyeee commented on src/api/auth.ts
> +    return response.data.token;
넵!!!!

2024-03-25 15:53 UTC, merged