마켓 무한스크롤 기능 구현
hyunyeee/mju-market pull request #16
Opened 2024-04-09 16:31 UTC by hyunyeee

## 📄 Summary
react-query useInfiniteQuery Hook을 사용한 무한스크롤 기능 구현

## 🙋🏻 More

2024-04-11 17:52 UTC, ndaemy requested changes
조금 수정하면 좋을 부분들이 있어서 Request changes 인데, 시간 리소스에 맞게 적당히 수정하고 merge 하면 될듯!

2024-04-11 17:52 UTC, ndaemy commented on src/App.tsx
> +const queryClient = new QueryClient();
앞으로 계속 같은 주소의 서버에 요청을 보낼거라면 defaultQueryFn 을 만들어서 주입해주는게 좋을거야
[참고](https://tanstack.com/query/v4/docs/framework/react/guides/default-query-function)

2024-04-11 17:52 UTC, ndaemy commented on src/api/market.ts
> +    `/api/categories/${categoryId + 1}/products?${productId ? `productId=${productId}&` : ''}pageSize=${pageSize}`,
음? product 하나만 조회하는 api 는 별도로 있어야 하는거 아니야..?

2024-04-11 17:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +  const token = localStorage.getItem('token') || '';
1. localStorage는 별도의 hook (ex. useLocalStorage) 을 만들어서 사용하는걸 추천하고 - 에러도 핸들링하고 (ex. 토큰이 localStorage 에 없다던가)
2. 로그인 토큰처럼 여기저기서 사용해야 하는 값은 한 번만 localStorage 에서 가져와서 전역상태로 관리하는걸 추천해

2024-04-11 17:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +    });
올~ 👍

2024-04-11 17:52 UTC, ndaemy commented on src/components/UI/market/SelectCategory.tsx
> +      <button onClick={() => fetchNextPage()}>다음 페이지</button>
아래처럼 simplify 할 수 있을듯

```suggestion
      <button onClick={fetchNextPage}>다음 페이지</button>
```

2024-04-11 17:52 UTC, ndaemy commented on src/hooks/useCategoryProductQuery.tsx
> +      getProducts(token, categoryId, pageParam, pageSize),
위에서도 한 리뷰인데, fetch 함수를 queryClient 에 default 로 넣어주는 방향으로 리팩토링 해두는걸 추천해. 앞으로 코드 짜는거 감안하면 그게 더 시간을 아끼는 방법일거야

2024-04-13 08:17 UTC, hyunyeee commented on src/api/market.ts
> +    `/api/categories/${categoryId + 1}/products?${productId ? `productId=${productId}&` : ''}pageSize=${pageSize}`,
이거 products 리스트 조회 하는 건데 맨 최근 페이지 요청할 때만 null로 들어가는 거에요,,!

2024-04-15 06:17 UTC, ndaemy requested changes
react-query 두 번 깔린거때문에 request changes 남겨여~

2024-04-15 06:17 UTC, ndaemy commented on package.json
> +    "react-query": "^3.39.3",
이거 삭제하세욧!!

2024-04-15 06:17 UTC, ndaemy commented on src/pages/Market.tsx
> +  const token = localStorage.getItem('token') || '';
여기도 localStorage hook 으로 빼면 좋을듯!

2024-04-17 13:24 UTC, hyunyeee commented on src/components/UI/market/SelectCategory.tsx
> +  const token = localStorage.getItem('token') || '';
훅 만들어봤습니다...!!!!!!!!!!~~!!!! 이제야 완성 했습니다 ,,!!!!

2024-04-17 13:26 UTC, hyunyeee commented on src/pages/Market.tsx
> +  const token = localStorage.getItem('token') || '';
넵 완완입니다 !!~~

2024-04-17 14:40 UTC, hyunyeee commented on package.json
> +    "react-query": "^3.39.3",
완완 했습니다...!!!!!!!!!~~~~~~!!!!

2024-04-17 16:02 UTC, merged